### ISSUE TITLE
crash when deleting profile folder

### ISSUE THREAD

**Issue by anlalalu** [passwordmaker/android-passwordmaker#47]
###### Reproduction Steps

1. tap 'more options'
2. tap 'profiles'
3. create a profile named profileA
4. create a folder named folderA
5. create a profile in folderA
6. go to profiles interface again
7. tap profileA
8. tap the folderA
9. tap 'delete'

###### Stack Trace
crash with the stack trace:

E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: org.passwordmaker.android, PID: 19124
                                                   java.lang.IndexOutOfBoundsException: Invalid index 2, size is 1
                                                       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                       at java.util.ArrayList.get(ArrayList.java:308)
                                                       at android.widget.ArrayAdapter.getItem(ArrayAdapter.java:337)
                                                       at org.passwordmaker.android.AccountListFragment.getCheckedAccount(AccountListFragment.java:449)
                                                       at org.passwordmaker.android.AccountListFragment$3.onActionItemClicked(AccountListFragment.java:425)
                                                       at android.support.v7.app.AppCompatDelegateImpl$ActionModeCallbackWrapperV9.onActionItemClicked(AppCompatDelegateImpl.java:2171)
                                                       at android.support.v7.view.StandaloneActionMode.onMenuItemSelected(StandaloneActionMode.java:141)
                                                       at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
                                                       at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
                                                       at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
                                                       at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981)
                                                       at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
                                                       at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
                                                       at android.view.View.performClick(View.java:4438)
                                                       at android.view.View$PerformClick.run(View.java:18422)
                                                       at android.os.Handler.handleCallback(Handler.java:733)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                       

###### Screen Shot
These are related screen shots:

<img width="446" alt="1" src="https://user-images.githubusercontent.com/46981872/72139471-eb755600-33c9-11ea-912a-a73810a5706a.png">
<img width="443" alt="2" src="https://user-images.githubusercontent.com/46981872/72139486-f03a0a00-33c9-11ea-8f94-072c20c467c6.png">
<img width="442" alt="3" src="https://user-images.githubusercontent.com/46981872/72139494-f29c6400-33c9-11ea-847c-95db63742851.png">
<img width="408" alt="4" src="https://user-images.githubusercontent.com/46981872/72139500-f5975480-33c9-11ea-80a4-77359b5248b9.png">

###### Debug info
App Version = the latest master branch

Android Version = 4.4.4

**Comment by anlalalu** [comment]
@tasermonkey do you judge this as a defect? If so, please let me know. Thank you!

**Comment by tasermonkey** [comment]
@anlalalu  - yes, I just don't have an android device, at this time.  

I don't think I would be able to look at it this week.

**Comment by anlalalu** [comment]
Thank you for your reply! Maybe I will try to fix it when I am free.
